# Generated by Django 2.2.1 on 2019-07-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='extra',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
