# Generated by Django 2.2.1 on 2019-07-28 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0003_auto_20190728_0057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventos',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='localidades',
            options={'verbose_name': 'Localidad', 'verbose_name_plural': 'Localidades'},
        ),
        migrations.AlterModelOptions(
            name='solicitante',
            options={'verbose_name': 'Solicitante', 'verbose_name_plural': 'Solicitantes'},
        ),
        migrations.AlterModelOptions(
            name='solicitud',
            options={'verbose_name': 'Solicitud', 'verbose_name_plural': 'Solicitudes'},
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='estatus',
        ),
        migrations.DeleteModel(
            name='Estatus',
        ),
    ]
