# Generated by Django 2.2.1 on 2019-07-30 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0005_auto_20190728_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud', to='solicitud.Eventos'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='extra',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
