# Generated by Django 2.2.1 on 2019-07-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0006_auto_20190730_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
